Install and use cargo-leptos

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -36,8 +36,10 @@ DIESEL_FLAGS=""
 RUST_CARGO_BUILD_FLAGS="--release"
 
 # Load our toolchain configuration, if any was specified.
-if [ -f "$BUILD_DIR/rust-toolchain" ]; then
-    VERSION="$(cat "$BUILD_DIR/rust-toolchain")"
+if [ -f "$BUILD_DIR/rust-toolchain.toml" ]; then
+    # Not the perfect solution, but I don't want to have to require a TOML
+    # parsing tool as well. This will have to do.
+    VERSION="$( cat "$BUILD_DIR/rust-toolchain.toml" | grep 'channel = ' | sed 's/^channel = "//' | sed 's/"$//' )"
 fi
 
 # Load our configuration variables, if any were specified.
@@ -50,7 +52,7 @@ set -eu
 
 # Check our configuration options.
 if [ -z ${VERSION+x} ]; then
-  >&2 echo "failed: must set VERSION with rust-toolchain or RustConfig to indicate the Rust version."
+  >&2 echo "failed: must set VERSION with rust-toolchain.toml or RustConfig to indicate the Rust version."
   exit 1
 fi
 
@@ -120,6 +122,12 @@ if [ ! -x "$CARGO_HOME/bin/rustc" ]; then
   exit 1
 fi
 
+# Install cargo-leptos if it is not already installed.
+cargo leptos --help 1>/dev/null 2>/dev/null
+if [ $? -ne 0 ]; then
+    cargo install --locked cargo-leptos
+fi
+
 # This is where we will cache our Rust output.  Note the suggestions at
 # https://github.com/alexcrichton/cargo/commit/014765f788ca1c2476936835ca32cc2746f99b42
 # which describe how this needs to be named.
@@ -134,14 +142,14 @@ if [ $RUST_SKIP_BUILD -ne 1 ]; then
   # To debug git issues:
   #export RUST_LOG="cargo::sources::git=debug"
   # To debug compiler and linking issues, add `--verbose`.
-  echo "-----> Building application using Cargo"
+  echo "-----> Building application using cargo-leptos"
   cd "$BUILD_DIR/$BUILD_PATH"
   rm -rf target/
-  cargo build $RUST_CARGO_BUILD_FLAGS
+  cargo leptos build $RUST_CARGO_BUILD_FLAGS
   mkdir -p target/release
   find "$CARGO_TARGET_DIR/release" -maxdepth 1 -type f -executable -exec cp -a -t target/release {} \;
 else
-  echo "-----> Skipping Cargo build"
+  echo "-----> Skipping cargo-leptos build"
 fi
 
 # Install diesel so we can use it for migrations
